CREATE TABLE Users(
`name` VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL PRIMARY KEY,
cash DECIMAL(15,2) NOT NULL DEFAULT 50000.00,
`password` VARCHAR(64) NOT NULL /* USE SHA256 */
);

CREATE TABLE Transactions(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
userID INT NOT NULL REFERENCES Users(email),
stock VARCHAR(10) NOT NULL,
pricePerStock DECIMAL(15,2) NOT NULL,
qty INT NOT NULL,
totalCost DECIMAL(15,2) NOT NULL,
`type` VARCHAR(4) NOT NULL,
`timestamp` DATETIME NOT NULL DEFAULT NOW()
);

CREATE TABLE Ownership(
userID INT NOT NULL REFERENCES Users(email),
stock VARCHAR(5) NOT NULL,
qty INT NOT NULL,
PRIMARY KEY (userID, stock)
);